plugins {
    id 'java'
}

group = 'sim.dmitriy'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.8.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.codeborne:selenide:6.19.1'
    testImplementation 'org.slf4j:slf4j-simple:2.0.12'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

test {
    useJUnitPlatform()
}